name: Release lib-version

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install build & publish tools
        run: |
          pip install --upgrade pip
          pip install build wheel twine setuptools_scm

      - name: Build package
        run: python -m build

      - name: Publish
        run: |
          twine upload \
            --repository-url https://upload.pkg.github.com/${{ github.repository_owner }}/lib-version \
            dist/*
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.GITHUB_TOKEN }}